name: Rails CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "Server@123"
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install gems
      run: bundle install

    - name: Setup DB
      run: |
        bundle exec rails db:create db:schema:load

    - name: Run tests
      run: bundle exec rails test

    - name: Run Rubocop
      run: bundle exec rubocop
      